import assert from "node:assert/strict";
import { getPointCount } from "../components/app-shell/message-draft-storage";
import { assembleDevelopMessageDraft, validateGeneratedDevelopMessage } from "../lib/message-generation/develop-assembly";
import { buildCuratedDevelopDraft } from "../lib/message-generation/develop-fallback";
import type { GeneratedDevelopMessage } from "../lib/message-generation/develop-schema";
import type { DevelopMessageGenerationInput } from "../lib/message-generation/develop-types";

function input(length: "30" | "45" | "60"): DevelopMessageGenerationInput { return { startingPath:"develop", startingPathLabel:"Develop My Message", messageMode:"sunday", messageModeLabel:"Sunday Sermon", length, lengthLabel:`${length} minutes`, translation:"King James Version, KJV", developIdea:"Hope in anxiety", developPassage:"Philippians 4:4-9", desiredResponse:"Pray instead of spiraling", direction:{ title:"Peace for a Divided Heart", scripture:"Philippians 4:4-9", bigIdea:"The peace of God guards what anxiety tries to occupy.", angle:"A message that gives practical spiritual shape to prayer, thought, and trust.", focus:"Calm, practice, and renewed attention." } }; }
const refs = ["Psalm 46:1","Isaiah 26:3","John 14:27","1 Peter 5:7","Romans 12:2","Philippians 4:6","2 Timothy 1:7","James 1:5","Romans 15:13","Hebrews 12:2"];
function generated(count:number): GeneratedDevelopMessage { return { title:"Peace That Stands Guard", contextNotes:["Philippians 4 moves from prayer to peace and practiced attention without shaming anxious people."], introduction:{ hook:"Many believers know what it is to love God while still feeling pulled apart by anxious thoughts.", pastoralTension:"The passage meets people carrying real concerns without treating worry as a reason for shame.", passageConnection:"Philippians 4:4-9 gives the congregation a Scripture-shaped path from anxiety toward prayer and peace.", bigIdeaBridge:"The peace of God guards what anxiety tries to occupy as the church brings burdens to Him.", explanation:"Paul gives worried believers a place to bring distress, a promise of guarding peace, and a way to train attention around what is true.", firstMovementTransition:"Begin by naming where anxious burdens can honestly go before God.", bullets:["Anxiety is named honestly.","The passage gives prayerful direction.","Peace guards the heart."], scripture:"Philippians 4:4-9" }, points:Array.from({length:count},(_,i)=>({ title:["Bring Burdens Honestly","Receive Guarding Peace","Practice True Attention","Choose Obedient Steps","Resist Fearful Spirals","Rest in Nearness","Ask for Wisdom","Walk With Hope","Look Toward Christ","Continue in Peace"][i], summary:"This movement develops the supporting Scripture in service of the main passage and big idea.", scripture:refs[i], bullets:["The text names a real need.","The text points toward faithful trust.","The text gives a concrete response."], explanation:"This supporting passage helps the congregation see how the main passage speaks into ordinary pressure without minimizing pain.", application:"Name one anxious place this week and bring it to God in prayer before choosing one faithful next step.", illustrationOptions:["A person setting down a heavy bag before a long walk.","A family pausing before a difficult conversation."], transition:"That honest response prepares the congregation for the next supporting truth." })), closing:{ recap:"Philippians 4 has moved the message from honest anxiety to prayer, peace, practiced attention, and faithful response.", callToResponse:"Call listeners to bring one named burden to God and take one concrete step of obedience this week.", closingApplication:"The peace of God guards what anxiety tries to occupy in real appointments, relationships, decisions, and fears.", prayer:"Ask the Lord to steady worried hearts, deepen trust in His Word, and guide the next faithful step.", bullets:["Bring the burden to God.","Receive His guarding peace.","Practice one faithful response."], scripture:"Romans 15:13" } }; }
for (const len of ["30","45","60"] as const) { const count=getPointCount(len); assert.equal(count, len==="30"?6:len==="45"?8:10); const issues=validateGeneratedDevelopMessage(input(len), generated(count)); assert.deepEqual(issues, []); const draft=assembleDevelopMessageDraft(input(len), generated(count)); assert.equal(draft.points.length, count); assert.ok(draft.points.every((p)=>p.id && p.notes==="")); assert.ok(draft.generationHistory?.pointTitles.includes(draft.points[0].title)); assert.ok(draft.generationHistory?.scriptureReferences.includes(draft.points[0].scripture)); assert.deepEqual(draft.scriptureBank.map((i)=>i.reference), [draft.mainScripture, draft.introduction.scripture, ...draft.points.map((p)=>p.scripture), draft.closing.scripture].filter(Boolean)); const fallback=buildCuratedDevelopDraft(input(len)); assert.equal(fallback.points.length, count); }
const dup=generated(6); dup.points[1].title=dup.points[0].title.toUpperCase(); assert.ok(validateGeneratedDevelopMessage(input("30"), dup).includes("duplicate-title"));
const missing=generated(6); missing.points[0].application=""; assert.ok(validateGeneratedDevelopMessage(input("30"), missing).includes("missing-application"));
const bad=generated(6); bad.points[0].scripture="NotABook 99:99"; assert.ok(validateGeneratedDevelopMessage(input("30"), bad).includes("bad-scripture"));
console.log("message generation checks passed");
